### ISSUE TITLE
fxdeviantart.com stopped working

### ISSUE THREAD

**Issue by EpicLPer** [robinuniverse/fxdeviantart#2]
Heya,

the site fxdeviantart.com stopped working, not sure if it's even hosted by yourself tho wanted to mention.

Thanks!

**Comment by coredumperror** [comment]
It's broken once again. Seems that the SSL cert has expired.

**Comment by daisyUniverse** [comment]
Apologies, I haven't looked at this in a while - will take a look when I get a chance to

EDIT: I believe I have gotten it taken care of, I do not currently have access to discord for testing, so please let me know if everything is running or not

**Comment by coredumperror** [comment]
Looks like it's working again! 

Though if you can, I do suggest that the next time you update it, you get a SAN cert that covers both www.fxdeviantart.com and fxdeviantart.com. Those are considered two different websites from a browser's SSL cert perspective, so they both need to be included in the cert, if that's possible with Let's Encrypt. I haven't personally used it, so I'm not sure.

**Comment by daisyUniverse** [comment]
Thank you! I will take a look at this next time I'm digging around in there 👍
