### ISSUE TITLE
Security certificate out-of-date, requires renewal.

### ISSUE THREAD

**Issue by Shockwave508** [robinuniverse/fxdeviantart#3]
Chrome is notifying me that FXDeviantArt's security certificate expired two days ago, and this embedder is now considered a security threat by the browser. Any chance you can fix this when you have the time?

**Comment by daisyUniverse** [comment]
Apologies for not seeing this, I've been quite unplugged for the last while - I believe I have fixed the cert issue ( one of my alternative domains expired and caused certbot to not autorenew the certificate, I removed the devxantart domain and reran certbot )

I do not have access to discord for testing, so please let me know if this is resolved or not

EDIT: Confirmed working in #2, closing issue
